### ISSUE TITLE
[BE] mock data 수정

### ISSUE THREAD

**Issue by 102092** [codesquad-member-2020/issue-tracker-03#46]
> side에 해당하는 API를 만들자

### issueReponse
- [x] GET : `api/issues ` 
- [x] 이슈에 해당하는 목록이 나오도록
- 변수명 조정

### label
- [x] GET: `api/labels`
- label 목록 반환

### author
- [x] GET: `api/authors`
- author 목록 반환

### milestones
- GET : `api/milestones`
- 마일스톤 목록 반환

### assignee
- [x] GET: `api/assignees` 
- assginee 가능한 유저 목록 반환 (가입된 유저)
- 아니면 author와 동일한 api 일듯
